# Use the specified image as the base
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

# Set the working directory in the container
WORKDIR /app

# Copy the local requirements.txt file to the container
COPY ./api/requirements.txt /app/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the current directory contents into the container
COPY . /app

# Run the FastAPI application using Uvicorn when the container launches
CMD ["uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "80"]
